name: Test & Lint

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 21
          cache: "npm"
      - name: Install dependencies
        run: npm ci
  storybook:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Install Playwright
        run: npx playwright install --with-deps
      - name: Build Storybook
        run: npm run test:build
      - name: Run Storybook tests
        run: npx run-p test:server test:storybook
  lint:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: ESLint
        run: npm run lint:eslint
      - name: Prettier
        run: npx run lint:prettier

  dependency-review:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout Repository"
        uses: actions/checkout@v3
      - name: "Dependency Review"
        uses: actions/dependency-review-action@v3
