name: Test & Lint

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  test-storybook:
    runs-on: ubuntu-latest

    steps:
      - uses: ./.github/workflows/install.yml
      - name: Install Playwright
        run: npx playwright install --with-deps
      - name: Build Storybook
        run: npm run test:build
      - name: Run Storybook tests
        run: npx run-p test:server test:storybook

  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: ./.github/workflows/install.yml
      - name: ESLint
        run: npm run lint:eslint
      - name: Prettier
        run: npx run lint:prettier

  dependency-review:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout Repository"
        uses: actions/checkout@v3
      - name: "Dependency Review"
        uses: actions/dependency-review-action@v3
